before_install:
    - yes | sudo add-apt-repository ppa:hansjorg/rust
    - sudo apt-get update
install:
    - sudo apt-get install rust-nightly
    - sudo apt-get install cabal-install
    - sudo apt-get install libgmp3-dev
script:
    - cd compiler/
    - cabal update
    - cabal install --only-dependencies --enable-tests
    - cabal configure --enable-tests && cabal build && cabal test
    - cp dist/build/scmc/scmc .
    - cd ../vm
    - git submodule init
    - git submodule update
    - rustc rust-gmp/gmp.rs `pkg-config --libs gmp`
    - rustc main.rs -Lrust-gmp/
    - cd ..
    - ./tests/run-tests.sh
